LIFEINSTITUTE/LIFEINSTITUTE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web'))
]

LIFEINSTITUTE/web/urls.py
from django.urls import path
from web.views import index, about, contact, com_course, dis_course

app_name = 'web'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('com-courses/', com_course, name='com_course'),
    path('dis-courses/', dis_course, name='dis_course'),
]

LIFEINSTITUTE/web/models.py
from django.db import models

# Create your models here.

class newsflash (models.Model):
    news = models.CharField(max_length=255)

    def __str__(self):
        return self.news
    
    

LIFEINSTITUTE/web/views.py
from django.shortcuts import render
from web.models import newsflash

# Create your views here.

def index (request):
    flashnews = newsflash.objects.all()
    context = {
        "flashnews" : flashnews
    }
    return render(request, 'pages/index.html', context=context)

def about (request):
    flashnews = newsflash.objects.all()
    context = {
        "flashnews" : flashnews
    }
    return render(request, 'pages/about.html', context=context)

def contact (request):
    return render(request, 'pages/contact.html')

def com_course (request):
    return render(request, 'pages/com-courses.html')

def dis_course (request):
    return render(request, 'pages/dis-courses.html')

LIFEINSTITUTE/templates/pages/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Life Institute | About</title>

    <!-- link CSS -->

    <link rel="stylesheet" href="{% static '/css/about.css' %}">

    <!-- Google Font Link -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- remix icon CDN -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css"/>
    
</head>
<body>
    <section id="header">
        <div class="logo">
            <img src="{% static '/assets/logo.png' %}" alt="Brand_logo">
        </div>
        <div class="menu">
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:about' %}">About</a></li>
                <li class="dropdown-c">Courses <i class="ri-arrow-down-s-line"></i>

                    <div class="dropdown">
                        <ul>
                            
                            <li><a href="{% url 'web:com_course' %}">Diploma & Computer Courses</a></li>
                            <li><a href="{% url 'web:dis_course' %}">Distance Courses</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="">Gallery</a></li>
                <li><a href="{% url 'web:contact' %}">Contact</a></li>
            </ul>
        </div>
    </section>

    <section id="main" class="c-back">
        <section id="head">
            <div class="img-text">
                <h1>We Are The Life Group Of Institute</h1>
            </div>
        </section>
    
        <section id="About-write">
            <h4>Our Thought</h4>
            <p>Our Core Aspiration is to provide an Educational Excellencs, in that every student makes a positive difference during the time with us. In expecting Excellencs we ensure that children enjoy institute in a happy, safe and secure atmosphere designed to fulfill their potential.</p>

            <h4>Director Message:</h4>
            <p> I am sure that our student will fint a pathway to a brightfuture to a closen career or any profession they also can get enough knwoladge to face any damand and challenges that an employer may have on them. I wish for their great success and bright future. </p>
        </section>

        
    </section>

    <section id="news_splash">
        <div class="new">
            <h4>Flash News</h4>
        </div>
        <div class="group">
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}

            
        </div>
    </section>

    


    <footer>
        <div class="m">
            <h6>Company <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="">LBS SKILL CENTER</a></li>
                    <li><a href="">LIFE GROUP OF INSTITUTION</a></li>
                    <li><a href="">Calicut University</a></li>
                    <li><a href="">Bharathiar University</a></li>
                    <li><a href="">Sreenarayana Guru Open University</a></li>
                    <li><a href=""><img src="{% static '/assets/LBS.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>URLS <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:index' %}">HOME PAGES</a></li>
                    <li><a href="{% url 'web:about' %}">ABOUT PAGES</a></li>
                    <li><a href="{% url 'web:com_course' %}">COURSES PAGES</a></li>
                    <li><a href="">GALLERY PAGES</a></li>
                    <li><a href="{% url 'web:contact' %}">CONTACT PAGES</a></li>
                    <li><a href=""><img src="{% static '/assets/logo.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        <div class="m">
            <h6>Courses <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:dis_course' %}">Distance Courses</a></li>
                    <li><a href="{% url 'web:com_course' %}">Diploma & Computer Courses</a></li>
                </ul>

                <h6 style="margin-top: 50px;">Most Popular Courses <span class="line">___</span></h6>

                <ul>
                    <li><a href="">Aritifial Inteligence</a></li>
                    <li><a href="">Certified Python Course</a></li>
                    <li><a href="">Certified Interial Design Course</a></li>
                    <li><a href="">Certified #D Printing Course</a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>Contact <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href=""><i class="ri-phone-line"></i>9539444557</a></li>
                    <li><a href=""><i class="ri-mail-line"></i>lifeinstitute@gmail.com</a></li>
                    <li><a href=""><i class="ri-map-pin-line"></i>Thrithla, Pattambi</a></li>
                    <li><a href="">Near Canara bank</a></li>
                </ul>
            </div>
        </div>
    </footer>

    

    <script src="{% static '/js/script.js' %}"></script>
</body>
</html>

LIFEINSTITUTE/templates/pages/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Life Institute | Contact</title>

    <!-- link CSS -->

    <link rel="stylesheet" href="{% static '/css/contact.css' %}">

    <!-- Google Font Link -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- remix icon CDN -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css"/>
</head>
<body>
    <section id="header">
        <div class="logo">
            <img src="{% static '/assets/logo.png' %}" alt="Brand_logo">
        </div>
        <div class="menu">
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:about' %}">About</a></li>
                <li class="dropdown-c">Courses <i class="ri-arrow-down-s-line"></i>

                    <div class="dropdown">
                        <ul>
                            
                            <li><a href="{% url 'web:com_course' %}">Diploma & Computer Course</a></li>
                            <li><a href="{% url 'web:dis_course' %}">Distance Course</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="">Gallery</a></li>
                <li><a href="{% url 'web:contact' %}">Contact</a></li>
            </ul>
        </div>
    </section>

    <section id="main">
        <iframe src="{% static 'https://www.google.com/maps/embed?pb=!3m2!1sen!2sin!4v1719674075320!5m2!1sen!2sin!6m8!1m7!1s1PV_u6xQA_myG_tadhXmbQ!2m2!1d10.80209493768133!2d76.12924137364027!3f240.42589595685678!4f19.97744732099308!5f0.7820865974627469" width="1020" height="480" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class="google-frame "></iframe>

        <header class="seperator-head text-center">
            <h2>Contact Details</h2>
            <p>Welcome to our Website. We are glad to have you around.</p>
            <hr class="head-line">
        </header>

        <div class="item">
            
            <ul>
               
                <li><i class="ri-phone-line"></i>Phone</li>
                <li><i class="ri-mail-line"></i>Email</li>
                <li><i class="ri-map-pin-line"></i>Location</li>

                
            </ul>

            <ul class="details">
                <li class="it">9539444557</li>
                <li class="it">Lifeinstitute@gmail.com</li>
                <li class="it">Koottanad Road, Thrithala</li>
            </ul>
            
        </div>
    </section>

    <footer>
        <div class="m">
            <h6>Company <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="">LBS SKILL CENTER</a></li>
                    <li><a href="">LIFE GROUP OF INSTITUTION</a></li>
                    <li><a href="">Calicut University</a></li>
                    <li><a href="">Bharathiar University</a></li>
                    <li><a href="">Sreenarayana Guru Open University</a></li>
                    <li><a href=""><img src="{% static '/assets/LBS.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>URLS <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:index' %}">HOME PAGES</a></li>
                    <li><a href="{% url 'web:about' %}">ABOUT PAGES</a></li>
                    <li><a href="com-courses.html">COURSES PAGES</a></li>
                    <li><a href="">GALLERY PAGES</a></li>
                    <li><a href="">CONTACT PAGES</a></li>
                    <li><a href=""><img src="{% static '/assets/logo.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        <div class="m">
            <h6>Courses <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="dis-course.html">Distance Courses</a></li>
                    <li><a href="com-courses.html">Diploma & Computer Courses</a></li>
                </ul>

                <h6 style="margin-top: 50px;">Most Popular Courses <span class="line">___</span></h6>

                <ul>
                    <li><a href="">Aritifial Inteligence</a></li>
                    <li><a href="">Certified Python Course</a></li>
                    <li><a href="">Certified Interial Design Course</a></li>
                    <li><a href="">Certified 3D Printing Course</a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>Contact <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href=""><i class="ri-phone-line"></i>9539444557</a></li>
                    <li><a href=""><i class="ri-mail-line"></i>lifeinstitute@gmail.com</a></li>
                    <li><a href=""><i class="ri-map-pin-line"></i>Thrithla, Pattambi</a></li>
                    <li><a href="">Near Canara bank</a></li>
                </ul>
            </div>
        </div>
    </footer>


    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

LIFEINSTITUTE/templates/pages/dis-courses.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Life Institute | Distance Courses</title>

    <!-- link style.css -->

    <link rel="stylesheet" href="{% static '/css/distance.css' %}">

    <!-- remix icon CDN -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css"/>

    <!-- link font family -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    
</head>

<body>
    <section id="header">
        <div class="logo">
            <img src="{% static '/assets/logo.png' %}" alt="Brand_logo">
        </div>
        <div class="menu">
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:about' %}">About</a></li>
                <li class="dropdown-c">Courses <i class="ri-arrow-down-s-line"></i>

                    <div class="dropdown">
                        <ul>
                            
                            <li><a href="{% url 'web:com_course' %}">Diploma & Computer Course</a></li>
                            <li><a href="{% url 'web:dis_course' %}">Distance Course</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="">Gallery</a></li>
                <li><a href="{% url 'web:contact' %}">Contact</a></li>
            </ul>
        </div>
    </section>

    <section id="Distance" class="c-back">
        <div class="uni calicut">

            <div class="uni-text">
                <h3>Calicut University</h3>

                <ul>
                    <li>B.COM</li>
                    <li>BBA</li>
                    <li>BA</li>
                    <li>MA</li>
                    <li>M.COM</li>
                    <li>B.COM</li>
                    <li>BBA</li>
                    <li>BA</li>
                    <li>MA</li>
                    <li>M.COM</li>
                </ul>
            </div>

            
            

            
        </div>

        

        <div class="uni sreenarayana">

            <div class="uni-text">
                <h3>Sreenarayana Guru <br>
                    Open University</h3>

            <ul>
                <li>B.COM</li>
                <li>BBA</li>
                <li>BA</li>
                <li>BSC MATHS</li>
                <li>MSC MATHS</li>
                <li>MA</li>
                <li>M.COM</li>
                <li>MSC MATHS</li>
                <li>MA</li>
                <li>M.COM</li>

                
            </ul>
            </div>

            
            
        </div>

        <div class="uni Bharathiar">

            <div class="uni-text">
                <h3>Bharathiar University <br>(Online \ ODL Programme)</h3>

            <ul>
                <li>B.COM</li>
                <li>BBA</li>
                <li>BSC MATHS</li>
                <li>MSC MATHS</li>
                <li>BA</li>
                <li>MA</li>
                <li>M.COM</li>
                <li>MBA</li>
                <li>MCA</li>
                
                <li>Applied Psycthology</li>
            </ul>
            </div>

            
        </div>

        
    </section>

    <hr>

    <section id="images">
        <img src="{% static '/assets/calicut.jpg' %}" alt="">
        <img src="{% static '/assets/baharathiar.jpg' %}" alt="">
        <img src="{% static '/assets/Sree_narayana.jpg' %}" alt="">
    </section>

    <footer>
        <div class="m">
            <h6>Company <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="">LBS SKILL CENTER</a></li>
                    <li><a href="">LIFE GROUP OF INSTITUTION</a></li>
                    <li><a href="">Calicut University</a></li>
                    <li><a href="">Bharathiar University</a></li>
                    <li><a href="">Sreenarayana Guru Open University</a></li>
                    <li><a href=""><img src="{% static '/assets/LBS.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>URLS <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:index' %}">HOME PAGES</a></li>
                    <li><a href="{% url 'web:about' %}">ABOUT PAGES</a></li>
                    <li><a href="{% url 'web:com_course' %}">COURSES PAGES</a></li>
                    <li><a href="">GALLERY PAGES</a></li>
                    <li><a href="{% url 'web:contact' %}">CONTACT PAGES</a></li>
                    <li><a href=""><img src="{% static '/assets/logo.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        <div class="m">
            <h6>Courses <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:dis_course' %}">Distance Courses</a></li>
                    <li><a href="{% url 'web:com_course' %}">Diploma & Computer Courses</a></li>
                </ul>

                <h6 style="margin-top: 50px;">Most Popular Courses <span class="line">___</span></h6>

                <ul>
                    <li><a href="">Aritifial Inteligence</a></li>
                    <li><a href="">Certified Python Course</a></li>
                    <li><a href="">Certified Interial Design Course</a></li>
                    <li><a href="">Certified #D Printing Course</a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>Contact <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href=""><i class="ri-phone-line"></i>9539444557</a></li>
                    <li><a href=""><i class="ri-mail-line"></i>lifeinstitute@gmail.com</a></li>
                    <li><a href=""><i class="ri-map-pin-line"></i>Thrithla, Pattambi</a></li>
                    <li><a href="">Near Canara bank</a></li>
                </ul>
            </div>
        </div>
    </footer>

    


    
    
    
              
       
    
      
      

    
    <script src="{% static '/js/script.js' %}"></script>
</body>
    
</html>

LIFEINSTITUTE/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Life Institute | Home</title>

    <!-- link CSS -->

    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    <!-- Google Font Link -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- remix icon CDN -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css"/>

    

</head>
<body>
    <section id="header">
        <div class="logo">
            <img src="{% static '/assets/logo.png' %}" alt="Brand_logo">
        </div>
        <div class="menu">
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:about' %}">About</a></li>
                <li class="dropdown-c">Courses <i class="ri-arrow-down-s-line"></i>

                    <div class="dropdown">
                        <ul>
                            <li><a href="{% url 'web:com_course' %}">Diploma & Computer Courses</a></li>
                            <li><a href="{% url 'web:dis_course' %}">Distance Courses</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="">Gallery</a></li>
                <li><a href="{% url 'web:contact' %}">Contact</a></li>
            </ul>
        </div>
    </section>

    <section id="Home" class="c-back">
        <div class="left-text">
            <h1>We Are Leading Life Group <br> Of Institution  Thrithala.</h1>
            <p>Our Core Aspiration is to provide an Educational Excellencs, in that every student makes a positive difference during the time with us. In expecting Excellencs we ensure that children enjoy institute in a happy, safe and secure atmosphere designed to fulfill their potential.</p>

            <div class="buttons">
                <a href="#" class="btn">Our Courses</a>
                <a href="#" class="btn">Contact Us</a>
            </div>
        </div>
        <div class="right-logo">
            <img src="{% static '/assets/images.jpg' %}" alt="Home-side-logo">
        </div>
    </section>

    <section id="onwer">
        <div class="left-img-onwer">
            <img src="{% static '/assets/RoyalCollegeChairman.jpg' %}">
            <span>Director: Ashrafali M</span>
        </div>
        <div class="right-details">
            
           
            <span>Director Message: </span>

            <p>
                I am sure that our student will fint a pathway to a brightfuture to a closen career or any profession they also can get enough knwoladge to face any damand and challenges that an employer may have on them. I wish for their great success and bright future. 
            </p>
        </div>
    </section>

    <section id="card">
        <h4>Most Popular Courses</h4>

        <div class="main-card">
            <div class="cards">
                <img src="{% static '/assets/card1.jpg' %}">
                <h2>Certificated Course in Artifial inteligence</h2>
                <span>plus two/3 year Diploma</span>
                <hr>
                <small>3 month</small>
            </div>
            <div class="cards">
                <img src="{% static '/assets/card2.jpg' %}">
                <h2>Certificated Course in Artifial inteligence</h2>
                <span>plus two/3 year Diploma</span>
                <hr>
                <small>3 month</small>
            </div>
            <div class="cards">
                <img src="{% static '/assets/card3.jpg' %}">
                <h2>Certificated Course in Artifial inteligence</h2>
                <span>plus two/3 year Diploma</span>
                <hr>
                <small>3 month</small>
            </div>
            <div class="cards">
                <img src="{% static '/assets/card4.jpg' %}">
                <h2>Certificated Course in Artifial inteligence</h2>
                <span>plus two/3 year Diploma</span>
                <hr>
                <small>3 month</small>
            </div>
        </div>
        
        
    </section>

    <section id="news_splash">
        <div class="new">
            <h4>Flash News</h4>
        </div>
        <div class="group">
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
                <span>{{flash.news}}</span>
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}
            {% for flash in flashnews %}
                <span>{{flash.news}}</span>
            {% endfor %}

            
        </div>
    </section>

    <footer>
        <div class="m">
            <h6>Company <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="">LBS SKILL CENTER</a></li>
                    <li><a href="">LIFE GROUP OF INSTITUTION</a></li>
                    <li><a href="">Calicut University</a></li>
                    <li><a href="">Bharathiar University</a></li>
                    <li><a href="">Sreenarayana Guru Open University</a></li>
                    <li><a href=""><img src="{% static '/assets/LBS.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>URLS <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:index' %}">HOME PAGES</a></li>
                    <li><a href="{% url 'web:about' %}">ABOUT PAGES</a></li>
                    <li><a href="{% url 'web:com_course' %}">COURSES PAGES</a></li>
                    <li><a href="">GALLERY PAGES</a></li>
                    <li><a href="{% url 'web:contact' %}">CONTACT PAGES</a></li>
                    <li><a href=""><img src="{% static '/assets/logo.png' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
        <div class="m">
            <h6>Courses <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href="{% url 'web:dis_course' %}">Distance Courses</a></li>
                    <li><a href="{% url 'web:com_course' %}">Diploma & Computer Courses</a></li>
                </ul>

                <h6 style="margin-top: 50px;">Most Popular Courses <span class="line">___</span></h6>

                <ul>
                    <li><a href="">Aritifial Inteligence</a></li>
                    <li><a href="">Certified Python Course</a></li>
                    <li><a href="">Certified Interial Design Course</a></li>
                    <li><a href="">Certified #D Printing Course</a></li>
                </ul>
            </div>
        </div>
        
        <div class="m">
            <h6>Contact <span class="line">___</span></h6>
            

            <div class="menu">
                <ul>
                    <li><a href=""><i class="ri-phone-line"></i>9539444557</a></li>
                    <li><a href=""><i class="ri-mail-line"></i>lifeinstitute@gmail.com</a></li>
                    <li><a href=""><i class="ri-map-pin-line"></i>Thrithla, Pattambi</a></li>
                    <li><a href="">Near Canara bank</a></li>
                </ul>
            </div>
        </div>
    </footer>

    

    

    <script src="{% static '/js/script.js' %}"></script>
</body>
</html>